export const DATE_FIXTURES = {
  now: "2026-05-09T00:00:00.000Z",
  pastDate: "2026-05-01T00:00:00.000Z",
  futureDate: "2026-06-01T00:00:00.000Z",
  midDate: "2026-05-15T00:00:00.000Z",
  endDate: "2026-05-20T00:00:00.000Z",
  finishedDate: "2026-05-08T00:00:00.000Z",
};

export const USER_FIXTURES = [
  {
    id: "seed-user-alice",
    name: "Alice",
    email: "alice@example.com",
    emailVerified: true,
    image: null,
  },
  {
    id: "seed-user-bob",
    name: "Bob",
    email: "bob@example.com",
    emailVerified: false,
    image: null,
  },
  {
    id: "seed-user-carol",
    name: "Carol",
    email: "carol@example.com",
    emailVerified: false,
    image: null,
  },
] as const;

export const PROJECT_FIXTURES = [
  {
    id: 1,
    name: "Website Redesign",
    description: "Redesign of the public marketing website",
    color: "#3B82F6",
  },
  {
    id: 2,
    name: "Mobile App",
    description: "Cross-platform mobile application",
    color: "#22C55E",
  },
  {
    id: 3,
    name: "Backend API",
    description: "REST API and infrastructure improvements",
    color: "#A855F7",
  },
] as const;

export const TASK_FIXTURES = [
  // Website Redesign tasks
  {
    id: 1,
    name: "Design landing page",
    description: "Create mockups for the new landing page",
    status: "NEW" as const,
    priority: "HIGH" as const,
    deadline: DATE_FIXTURES.futureDate,
    finishedAt: null,
    createdAt: DATE_FIXTURES.now,
    updatedAt: DATE_FIXTURES.now,
    projectId: 1,
    userId: "seed-user-alice",
  },
  {
    id: 2,
    name: "Implement responsive layout",
    description: "Build the new layout with Tailwind CSS",
    status: "IN_PROGRESS" as const,
    priority: "MEDIUM" as const,
    deadline: DATE_FIXTURES.midDate,
    finishedAt: null,
    createdAt: DATE_FIXTURES.pastDate,
    updatedAt: DATE_FIXTURES.now,
    projectId: 1,
    userId: "seed-user-alice",
  },
  {
    id: 3,
    name: "Write copy for about page",
    description: null,
    status: "STOPPED" as const,
    priority: "LOW" as const,
    deadline: DATE_FIXTURES.endDate,
    finishedAt: null,
    createdAt: DATE_FIXTURES.pastDate,
    updatedAt: DATE_FIXTURES.pastDate,
    projectId: 1,
    userId: "seed-user-bob",
  },
  {
    id: 4,
    name: "SEO audit",
    description: "Review and fix SEO issues on existing pages",
    status: "FINISHED" as const,
    priority: "HIGH" as const,
    deadline: null,
    finishedAt: DATE_FIXTURES.finishedDate,
    createdAt: DATE_FIXTURES.pastDate,
    updatedAt: DATE_FIXTURES.finishedDate,
    projectId: 1,
    userId: "seed-user-carol",
  },
  // Mobile App tasks
  {
    id: 5,
    name: "Set up React Native project",
    description: "Initialize project and configure dependencies",
    status: "NEW" as const,
    priority: "MEDIUM" as const,
    deadline: DATE_FIXTURES.futureDate,
    finishedAt: null,
    createdAt: DATE_FIXTURES.now,
    updatedAt: DATE_FIXTURES.now,
    projectId: 2,
    userId: "seed-user-bob",
  },
  {
    id: 6,
    name: "Build authentication screens",
    description: "Login, register and forgot password screens",
    status: "IN_PROGRESS" as const,
    priority: "HIGH" as const,
    deadline: DATE_FIXTURES.midDate,
    finishedAt: null,
    createdAt: DATE_FIXTURES.pastDate,
    updatedAt: DATE_FIXTURES.now,
    projectId: 2,
    userId: "seed-user-bob",
  },
  {
    id: 7,
    name: "Integrate push notifications",
    description: null,
    status: "STOPPED" as const,
    priority: "MEDIUM" as const,
    deadline: DATE_FIXTURES.endDate,
    finishedAt: null,
    createdAt: DATE_FIXTURES.pastDate,
    updatedAt: DATE_FIXTURES.pastDate,
    projectId: 2,
    userId: "seed-user-alice",
  },
  {
    id: 8,
    name: "Submit to App Store",
    description: "Prepare assets and submit for review",
    status: "FINISHED" as const,
    priority: "LOW" as const,
    deadline: null,
    finishedAt: DATE_FIXTURES.finishedDate,
    createdAt: DATE_FIXTURES.pastDate,
    updatedAt: DATE_FIXTURES.finishedDate,
    projectId: 2,
    userId: "seed-user-carol",
  },
  // Backend API tasks
  {
    id: 9,
    name: "Add rate limiting middleware",
    description: "Protect endpoints from abuse with rate limiting",
    status: "NEW" as const,
    priority: "LOW" as const,
    deadline: DATE_FIXTURES.futureDate,
    finishedAt: null,
    createdAt: DATE_FIXTURES.now,
    updatedAt: DATE_FIXTURES.now,
    projectId: 3,
    userId: "seed-user-carol",
  },
  {
    id: 10,
    name: "Implement pagination",
    description: "Add cursor-based pagination to list endpoints",
    status: "IN_PROGRESS" as const,
    priority: "MEDIUM" as const,
    deadline: DATE_FIXTURES.midDate,
    finishedAt: null,
    createdAt: DATE_FIXTURES.pastDate,
    updatedAt: DATE_FIXTURES.now,
    projectId: 3,
    userId: "seed-user-carol",
  },
  {
    id: 11,
    name: "Write API documentation",
    description: "Document all endpoints with OpenAPI spec",
    status: "STOPPED" as const,
    priority: "HIGH" as const,
    deadline: DATE_FIXTURES.endDate,
    finishedAt: null,
    createdAt: DATE_FIXTURES.pastDate,
    updatedAt: DATE_FIXTURES.pastDate,
    projectId: 3,
    userId: "seed-user-alice",
  },
  {
    id: 12,
    name: "Set up CI/CD pipeline",
    description: "Configure GitHub Actions for automated deploys",
    status: "FINISHED" as const,
    priority: "LOW" as const,
    deadline: null,
    finishedAt: DATE_FIXTURES.finishedDate,
    createdAt: DATE_FIXTURES.pastDate,
    updatedAt: DATE_FIXTURES.finishedDate,
    projectId: 3,
    userId: "seed-user-bob",
  },
] as const;
